apiVersion: apps/v1
kind: Deployment
metadata:
  name: loksai-eta-deploy
  labels:
    app: NETFLIX-1.2.2.war
spec:
  replicas: 3
  selector:
    matchLabels:
      app: NETFLIX-1.2.2.war
  template:
    metadata:
      labels:
        app: NETFLIX-1.2.2.war
    spec:
      containers:
      - name: netflix-container
        image: gowrisiva/netflix
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-np-service
  labels:
    app: NETFLIX-1.2.2.war
spec:
  selector:
    app: NETFLIX-1.2.2.war

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
