apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deploy
  labels:
    app: gowrisiva/netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowrisiva/netflix
  template:
    metadata:
      labels:
        app: gowrisiva/netflix
    spec:
      containers:
      - name: netflix-container
        image: gowrisiva/netflix
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-np-service
  labels:
    app: gowrisiva/netflix
spec:
  selector:
    app: gowrisiva/netflix

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
